/// POS UI catalog. Restaurant-entered names, notes and PIN values are not
/// translated. Keys retain the existing Georgian copy for migration stability.
const posEnglish = <String, String>{
  'აპლიკაციიდან გასვლა': 'Quit application',
  'ნამდვილად გსურთ Vynic POS-ის დახურვა?':
      'Are you sure you want to close Vynic POS?',
  'მონაცემები ინახება და კავშირები იხურება…':
      'Saving local data and closing connections…',
  'გაუქმება': 'Cancel',
  'გასვლა': 'Quit',
  'დახურვა': 'Close',
  'შენახვა': 'Save',
  'გასუფთავება': 'Clear',
  'წაშლა': 'Backspace',
  'გამოიყენეთ ფიზიკური კლავიატურა': 'Use your physical keyboard',
  'კლავიატურა': 'Keyboard',
  'ტექსტის შეყვანა': 'Enter text',
  'გამოტოვება': 'Space',
  'შეყვანა': 'Enter',
  'დადასტურება': 'Confirm',
  'მზადაა': 'Done',
  'სივრცე': 'Space',
  'PIN კოდი': 'PIN code',
  'შეიყვანეთ თანამშრომლის PIN': 'Enter your staff PIN',
  'შესვლა': 'Sign in',
  'მოწმდება...': 'Checking…',
  'ტერმინალი ჩაკეტილია': 'Terminal locked',
  'გასაგრძელებლად შეიყვანეთ PIN კოდი': 'Enter your PIN to continue',
  'არასწორი PIN კოდი': 'Incorrect PIN',
  'სრული გასვლა': 'Sign out',
  'PIN კოდი უნდა იყოს 6 ციფრი': 'PIN must contain 6 digits',
  'ეს PIN კოდი უკვე გამოიყენება': 'This PIN is already in use',
  'რესტორნის მართვის სისტემა': 'Restaurant management system',
  'შედით PIN კოდით და გააგრძელეთ მაგიდების, შეკვეთებისა და მენიუს მართვა.':
      'Sign in with your PIN to manage tables, orders and menus.',
  'ფილიალი': 'Branch',
  'მისამართი': 'Address',
  'ტერმინალი': 'Terminal',
  'დაუკავშირებელი': 'Not paired',
  'სამუშაო დღე': 'Business day',
  'სამუშაო თარიღი': 'Work date',
  'სისტემა': 'System',
  'მზად არის შესვლისთვის': 'Ready to sign in',
  'მენეჯერის აპი': 'Manager app',
  'ვერსია': 'Version',
  'მაგიდები': 'Tables',
  'მენიუ': 'Menu',
  'შეკვეთები': 'Orders',
  'ჯავშნები': 'Reservations',
  'ჯავშნები / მოლოდინი': 'Reservations / waiting',
  'წაღება': 'Takeaway',
  'კალკულატორი': 'Calculator',
  'მართვის ცენტრი': 'Management Center',
  'პარამეტრები': 'Settings',
  'პროგრამის შესახებ': 'About',
  'პროგრამის განახლება': 'Software update',
  'რესტორნის პარამეტრები': 'Restaurant settings',
  'თანამშრომლები': 'Staff',
  'გაყიდვები': 'Sales',
  'მარაგები': 'Inventory',
  'ხარჯები': 'Expenses',
  'ანგარიშები': 'Reports',
  'ფინანსები': 'Financials',
  'ისტორია': 'History',
  'დღის დახურვა': 'Close day',
  'შეტყობინებები': 'Notifications',
  'ახალი ჯავშანი': 'New reservation',
  'ჯავშნის შექმნა': 'Create reservation',
  'შექმნა': 'Create',
  'სტუმრის სახელი': 'Guest name',
  'შეიყვანეთ სახელი': 'Enter name',
  'ტელეფონი': 'Phone',
  'ტელეფონის ნომერი': 'Phone number',
  'შეიყვანეთ ტელეფონის ნომერი': 'Enter phone number',
  'სტუმრების რაოდენობა': 'Guest count',
  'შეიყვანეთ სტუმრების რაოდენობა': 'Enter guest count',
  'შენიშვნები': 'Notes',
  'დამატებითი ინფორმაცია...': 'Additional information…',
  'დრო': 'Time',
  'საათი:წუთი': 'Hour:minute',
  'თარიღი': 'Date',
  'მაგიდა': 'Table',
  'აირჩიეთ მაგიდა': 'Choose a table',
  'სახელი': 'Name',
  'რაოდენობა': 'Quantity',
  'ფასი': 'Price',
  'დამატება': 'Add',
  'რედაქტირება': 'Edit',
  'ძებნა': 'Search',
  'პროდუქტის ძებნა': 'Search products',
  'მარაგები ჯერ არ ჩამოტვირთულა': 'Inventory has not downloaded yet',
  'მონაცემები ბოლო განახლების დროისთვის. ცვლილებები შეიტანეთ მენეჯერის აპში.':
      'Data from the last refresh. Make changes in Manager.',
  'ყველა პროდუქტი': 'All products',
  'დაბალი მარაგი': 'Low stock',
  'უარყოფითი მარაგი': 'Negative stock',
  'ყველა': 'All',
  'შესაბამისი პროდუქტი ვერ მოიძებნა': 'No matching products found',
  'საკვები': 'Food',
  'სასმელი': 'Beverage',
  'აქტიური': 'Active',
  'არააქტიური': 'Inactive',
  'კატეგორია': 'Category',
  'კატეგორიები': 'Categories',
  'ახალი კატეგორია': 'New category',
  'ქვეკატეგორია': 'Subcategory',
  'ახალი პროდუქტი': 'New product',
  'დასახელება': 'Name',
  'აღწერა': 'Description',
  'ერთეული': 'Unit',
  'თანხა': 'Amount',
  'ჯამი': 'Total',
  'დაბრუნება': 'Back',
  'შემდეგი': 'Next',
  'განახლება': 'Refresh',
  'დასრულება': 'Finish',
  'თანამშრომლის დამატება': 'Add staff member',
  'ახალი თანამშრომელი': 'New staff member',
  'თანამშრომლის სახელი': 'Staff name',
  'მომხმარებლის სახელი': 'Username',
  'როლი': 'Role',
  'PIN-ის შეცვლა': 'Change PIN',
  'PIN კოდის შეცვლა': 'Change PIN',
  'PIN დაცულია': 'PIN protected',
  'აირჩიეთ PIN': 'Choose PIN',
  'შეიყვანეთ PIN': 'Enter PIN',
  'წვდომა': 'Access',
  'უფლებები': 'Permissions',
  'მოქმედებები': 'Actions',
  'აქტივობა': 'Activity',
  'ენა': 'Language',
  'ინტერფეისის ენა': 'Interface language',
  'ქართული': 'Georgian',
  'ინგლისური': 'English',
  'ეკრანის კლავიატურა': 'On-screen keyboard',
  'ეკრანული კლავიატურა': 'On-screen keyboard',
  'ჩართულია': 'Enabled',
  'გამორთულია': 'Disabled',
  'ჩართვა': 'Enable',
  'გამორთვა': 'Disable',
  'მიმდინარეობს...': 'Working…',
  'იტვირთება...': 'Loading…',
  'ინახება...': 'Saving…',
  'დააჭირეთ ციფრებს შესაყვანად': 'Tap digits to enter a value',
  'დააჭირეთ ციფრებს ან ?': 'Tap digits or ?',
  'წინ': 'Next',
  'უკან': 'Back',
  'რესტორანი': 'Restaurant',
  'გადახდა': 'Payment',
  'ნაღდი': 'Cash',
  'ბარათი': 'Card',
  'დამატებითი პარამეტრები': 'More settings',
  'გაყიდვების ისტორია': 'Sales history',
  'აქტივობის ჟურნალი': 'Activity log',
  'შემოსავალი': 'Revenue',
  'თანამშრომელი': 'Staff member',
  'პოზიცია': 'Item',
  'კომენტარი': 'Comment',
  'დასახელება ქართულად': 'Name in Georgian',
  'დასახელება ინგლისურად': 'Name in English',
  'საძიებო სიტყვა': 'Search term',
  'ფილტრი': 'Filter',
  'ფილტრები': 'Filters',
  'დღეს': 'Today',
  'PIN (6 ციფრი)': 'PIN (6 digits)',
  'PIN კოდი უნიკალური უნდა იყოს. მენეჯერი მართავს ყველა როლს, სუპერვაიზერი კი მხოლოდ ოფიციანტებს.':
      'PINs must be unique. Managers manage all roles; supervisors manage waiters only.',
  'ადმინ ავტორიზაცია': 'Admin verification',
  'აირჩიე ბიზნეს თარიღი': 'Choose business date',
  'აირჩიეთ თანამშრომლის ახალი წვდომის დონე.':
      'Choose the new staff access level.',
  'ამ განყოფილებაში შეგიძლიათ მხოლოდ ოფიციანტების მართვა:\n':
      'You can manage waiters only in this section:\n',
  'ამ კატეგორიაში ჯერ არ არის პროდუქტები': 'No products in this category yet',
  'აქვს ვარიანტები?': 'Has variants?',
  'აქტიური მიბმა არ არის': 'No active link',
  'აქტიური რეცეპტი / მიბმა': 'Active recipe / link',
  'აღდგენა დასრულდა': 'Restore completed',
  'ბოლო 100 დადასტურებული მიღება': 'Last 100 posted receipts',
  'ბოლო მოძრაობები (მაქს. 20)': 'Recent movements (up to 20)',
  'გაგრძელება': 'Continue',
  'გადასვლა': 'Open',
  'გამოიყენება მენიუში': 'Used in menu',
  'გამორთეთ ბარის პროდუქტებისთვის': 'Disable for bar products',
  'გამორთეთ ბარის/სასმელი კატეგორიებისთვის':
      'Disable for bar / beverage categories',
  'გაუქმების დადასტურების პაროლი': 'Cancellation confirmation password',
  'დახურვის დადასტურება': 'Confirm closing',
  'დახურვის ჩეკზე ასახვა': 'Show on closing receipt',
  'დღის მიღებები': 'Daily receipts',
  'ეს ეხება მხოლოდ იმ ჩეკს, რომელიც მაგიდის დახურვისას იბეჭდება ':
      'This applies only to the receipt printed when closing a table ',
  'ეს ქმედება გახსნის არჩეულ ბიზნეს დღეს, რათა შეძლო შეკვეთების და ჯავშნების კორექტირება.':
      'This opens the selected business day for adjusting orders and reservations.',
  'ვარიანტის დამატება': 'Add variant',
  'ვრცელდება ამ კატეგორიის ყველა პროდუქტზე':
      'Applies to every product in this category',
  'თანამშრომელი ვერ მოიძებნა': 'Staff member not found',
  'თანამშრომლების სია': 'Staff list',
  'თარიღის დადასტურება': 'Confirm date',
  'თვეების კორექცია': 'Month adjustment',
  'კატეგორიები ჯერ არ არის': 'No categories yet',
  'კატეგორიების მართვა': 'Manage categories',
  'კატეგორიის წაშლა': 'Delete category',
  'მაგალითი: ჩართულ რეჟიმში, ოფიციანტი A-ს გახსნილ მაგიდას ოფიციანტი B ვერ დახურავს.':
      'When enabled, waiter B cannot close a table opened by waiter A.',
  'მაგიდაზე დაბრუნება': 'Return to table',
  'მართეთ კატეგორიები, პროდუქტები, ფასები და სამზარეულოს მარშრუტები.':
      'Manage categories, products, prices and kitchen routing.',
  'მენეჯერი': 'Manager',
  'მენიუს პროდუქტები': 'Menu products',
  'მიმდინარე': 'Current',
  'მიმოხილვა': 'Overview',
  'მიუბმელი გაყიდული პროდუქტები': 'Unmapped sold products',
  'მოძრაობების ჩასატვირთად საჭიროა განახლება': 'Refresh to load movements',
  'მხოლოდ ჩეკის ვიზუალი იცვლება — ჯამური თანხა და ანგარიშები უცვლელია.':
      'Only receipt appearance changes; totals and reports stay the same.',
  'ნაგულისხმევი საკომისიო': 'Default service charge',
  'ოფიციანტი': 'Waiter',
  'პარამეტრის შენახვა ვერ მოხერხდა. სცადეთ ხელახლა.':
      'Could not save the setting. Try again.',
  'პერსონალი': 'Staff',
  'პროდუქტები იგზავნება სამზარეულოში': 'Products are sent to the kitchen',
  'პროდუქტი ვერ მოიძებნა': 'Product not found',
  'პროდუქტი იგზავნება სამზარეულოში': 'Product is sent to the kitchen',
  'პროდუქტის დამატება': 'Add product',
  'პროდუქტის წაშლა': 'Delete product',
  'რესტორნის კონფიგურაცია, უსაფრთხოება და წვდომის უფლებები.':
      'Restaurant configuration, security and access permissions.',
  'რეცეპტები და მიბმები': 'Recipes and links',
  'რეცეპტების სტატუსის ჩასატვირთად საჭიროა განახლება':
      'Refresh to load recipe status',
  'როლები და წვდომა': 'Roles and access',
  'როლის შეცვლა': 'Change role',
  'სამზარეულო': 'Kitchen',
  'სახელის შეცვლა': 'Rename',
  'სუპერვაიზერი': 'Supervisor',
  'სუპერვაიზერის შეზღუდვები': 'Supervisor restrictions',
  'ტექსტისა და რიცხვების შეყვანა ამ POS-ზე. შესვლისა და ჩაკეტვის PIN პანელი ყოველთვის ხელმისაწვდომია.':
      'Touch text and number input on this POS. Login and lock PIN pads are always available.',
  'ქვეკატეგორიაში პროდუქტები არ არის': 'No products in this subcategory',
  'ქვეკატეგორიები': 'Subcategories',
  'ქვეკატეგორიები არ არის': 'No subcategories',
  'ქვეკატეგორიის დამატება': 'Add subcategory',
  'ქვეკატეგორიის წაშლა': 'Delete subcategory',
  'ყველა ცვლილება ინახება მოქმედების დასრულებისთანავე.':
      'Changes are saved when each action completes.',
  'შეიყვანეთ ადმინის PIN კოდი': 'Enter admin PIN',
  'შეფასება წინასწარია': 'Provisional valuation',
  'ჩეკზე ასახვა': 'Show on receipt',
  'ცვლილებები არ არის შენახული. ნამდვილად გსურთ დახურვა?':
      'Changes are not saved. Close anyway?',
  'ცვლილებები ინახება მენიუს რედაქტირების დასრულებისთანავე.':
      'Changes are saved when menu editing completes.',
  'ცვლილებები ინახება შესაბამის ბლოკში. ტექსტისა და ციფრების ველები იყენებს ახალ POS კლავიატურას.':
      'Save changes in each section. Text and number fields use the shared POS keyboard.',
  'ძირითადი პროდუქტები': 'Main products',
  'ფასი (₾)': 'Price (₾)',
  'ვერსია {version}': 'Version {version}',
  'რეზერვაციები': 'Reservations',
  'ახალი რეზერვაცია': 'New reservation',
  'რეზერვაციის შექმნა': 'Create reservation',
  'პაკეტები': 'Packages',
  'ეკრანი': 'Display',
  'გაყიდვების რეპორტი': 'Sales report',
  'ფინანსური რეპორტები': 'Financial reports',
  'აუდიტი': 'Audit',
  'შეცდომები': 'Errors',
  'პრინტერები': 'Printers',
  'კავშირი': 'Connection',
  'დეველოპერი': 'Developer',
  'რესტორნის მონაცემები': 'Restaurant details',
  'მომსახურების საკომისიო': 'Service charge',
  'გაუქმების პაროლი': 'Cancellation password',
  'მაგიდის დახურვის უფლებები': 'Table closing permissions',
  'ენის პარამეტრები': 'Language settings',
  'სარეზერვო ასლი': 'Backup',
  'POS კლავიატურა': 'POS keyboard',
  'საკომისიო': 'Service charge',
  'გაუქმების დაცვა': 'Cancellation protection',
  'საკომისიოს პროცენტი': 'Service charge percentage',
  'მიმდინარე პაროლი': 'Current password',
  'ახალი პაროლი (6 ციფრი)': 'New password (6 digits)',
  'გაიმეორეთ ახალი პაროლი': 'Repeat new password',
  'პაროლის მინიშნება': 'Password hint',
  'ძებნა პროდუქტით ან კატეგორიით...': 'Search products or categories…',
  'ძებნა სახელით ან როლით...': 'Search by name or role…',
  'პაკეტის სახელი': 'Package name',
  'პაკეტის ასლი': 'Package copy',
  'აღწერა (სურვილისამებრ)': 'Description (optional)',
  'ერთ ადამიანზე ფასი (GEL)': 'Price per person (GEL)',
  'პროდუქტების ძიება': 'Search products',
  'სახელი (ქართული)': 'Name (Georgian)',
  'სახელი (ინგლისური)': 'Name (English)',
  'სლაგი': 'Slug',
  'ყველა ოფიციანტი': 'All waiters',
  'სულ თანამშრომლები': 'Total staff',
  'ახალი ოფიციანტი': 'New waiter',
  'ოფიციანტების დამატება და PIN-ების მართვა.': 'Add waiters and manage PINs.',
  'მართეთ თანამშრომლები, როლები და PIN-ები.': 'Manage staff, roles and PINs.',
  'არა': 'No',
  'არჩეული': 'Selected',
  'არჩეული მაგიდები': 'Selected tables',
  'აქ დაელოდება': 'Waiting here',
  'აქტიური შეკვეთები': 'Active orders',
  'ახალი გატანის შეკვეთა': 'New takeaway order',
  'ახალი ვერსია': 'New version',
  'ბეჭდვა': 'Print',
  'ბოლო განახლება ვერ დასრულდა — წინა ვერსია აღდგენილია.':
      'The last update failed; the previous version was restored.',
  'გააგრძელეთ მენიუში შეკვეთის შესაქმნელად':
      'Continue to the menu to create an order',
  'გადასახდელი': 'Amount due',
  'გადახდილი': 'Paid',
  'განახლება ახლა': 'Update now',
  'გატანები': 'Takeaway',
  'გატანის დეტალები': 'Takeaway details',
  'გატანის დრო': 'Pickup time',
  'დაამატე ახალი გატანის შეკვეთა, რომ სია შეივსოს.':
      'Add a takeaway order to get started.',
  'დაგვიანებული': 'Late',
  'დადასტურებული დაჯავშნები აქ გამოჩნდება':
      'Confirmed reservations appear here',
  'დაკავებული': 'Occupied',
  'დაყენებული ვერსია': 'Installed version',
  'დაჯავშნილი': 'Reserved',
  'დაჯავშნული სუფრების მართვა და წინასწარი შეკვეთები.':
      'Manage reserved tables and advance orders.',
  'დეტალები': 'Details',
  'დროის შეყვანა': 'Enter time',
  'დღევანდელი': 'Today',
  'დღევანდელი შეკვეთების მართვა და სტატუსების კონტროლი.':
      'Manage today\'s orders and their status.',
  'დღიური შემოსავალი': 'Daily revenue',
  'თავისუფალი': 'Available',
  'თუ პრობლემა გრძელდება, გახსენით Vynic Setup და აირჩიეთ აღდგენა.':
      'If the problem continues, open Vynic Setup and choose Repair.',
  'მენიუს ნახვა': 'View menu',
  'მენიუს შეცვლა': 'Edit menu',
  'მენიუში გადასვლა': 'Open menu',
  'მოგვიანებით': 'Later',
  'მონაცემები და განახლება': 'Data and updates',
  'ნომრის შეყვანა': 'Enter number',
  'პროდუქტები': 'Products',
  'პროდუქტები ჯერ არ არის დამატებული': 'No products added yet',
  'რეზერვაცია': 'Reservation',
  'რეზერვაციები არ არის': 'No reservations',
  'რეზერვაციის შეცვლა': 'Edit reservation',
  'სამზარეულოში გაგზავნა': 'Send to kitchen',
  'სართული': 'Floor',
  'სრული დეტალები': 'Full details',
  'სტატუსის შემოწმება': 'Check status',
  'სტუმრები': 'Guests',
  'სულ': 'Total',
  'სუფრაზე': 'At table',
  'სუფრაზე გადაყვანა': 'Move to table',
  'ტერმინალის ინფორმაცია': 'Terminal information',
  'შეკვეთა': 'Order',
  'შეკვეთის გაუქმება': 'Cancel order',
  'შეკვეთის დაწყება': 'Start order',
  'შეკვეთის დახურვა': 'Close order',
  'ჩეკის ბეჭდვა': 'Print receipt',
  'წინასწარი შეკვეთა': 'Advance order',
  'წინასწარი შეკვეთა ჯერ არ არის': 'No advance order yet',
  'ხელახლა შემოწმება': 'Check again',
  'ჯერ არ არის გატანის შეკვეთები': 'No takeaway orders yet',
  'აირჩიეთ ნაგულისხმევი ენა მენიუს, კლავიატურისა და ბეჭდური ჩეკებისთვის.':
      'Choose the language for menus, keyboards and printed receipts.',
  'ახალი ქვეკატეგორია': 'New subcategory',
  'ბიზნეს თარიღის შეცვლა': 'Change business date',
  'განაახლეთ მომსახურების საკომისიოს პროცენტი და განსაზღვრეთ ავტომატური გამოყენება.':
      'Set the service charge percentage and automatic application.',
  'განსაზღვრეთ, შეუძლია თუ არა ყველა ოფიციანტს მაგიდის დახურვა, თუ მხოლოდ მის შემქმნელს.':
      'Choose whether all waiters or only the creator can close a table.',
  'გაყიდვის გაუქმება': 'Cancel sale',
  'დათვლა': 'Calculate',
  'ზომა (მლ)': 'Size (ml)',
  'თანამშრომლების ხარჯი': 'Staff expense',
  'კატეგორიის რედაქტირება': 'Edit category',
  'მართეთ დადასტურების პაროლი, რომელიც საჭიროა შეკვეთის გაუქმებამდე.':
      'Manage the confirmation password required before cancelling an order.',
  'მენიუ ცარიელია': 'Menu is empty',
  'მენიუს დათვლა': 'Menu calculator',
  'მიზეზი': 'Reason',
  'პროდუქტის რედაქტირება': 'Edit product',
  'სამზარეულო გამორთული': 'Kitchen disabled',
  'სამზარეულო ჩართული': 'Kitchen enabled',
  'სახელი, მისამართი, ტელეფონი და ლოგო — ჩეკის თავში იბეჭდება.':
      'Name, address, phone and logo printed on the receipt header.',
  'სლაგი (მაგ. espresso-based)': 'Slug (e.g. espresso-based)',
  'სლაგი (მაგ. hot-drinks)': 'Slug (e.g. hot-drinks)',
  'სულ პროდუქტები': 'Total products',
  'ქვეკატეგორიის რედაქტირება': 'Edit subcategory',
  'ქირის ხარჯი': 'Rent expense',
  'შექმენით ბაზის სრული ასლი და შეინახეთ უსაფრთხო ':
      'Create a full database backup and keep it safe ',
  'პროგრამა განახლებულია': 'Up to date',
  'მოწმდება ახალი ვერსია': 'Checking for updates',
  'ახალი ვერსია იტვირთება': 'Downloading update',
  'ახალი ვერსია ხელმისაწვდომია': 'Update available',
  'განახლება დროებით შეუძლებელია': 'Update temporarily blocked',
  'მიმდინარეობს განახლება': 'Installing update',
  'პროგრამა თავიდან ირთვება': 'Restarting POS',
  'პროგრამა განახლდა': 'Update completed',
  'განახლება ვერ დასრულდა': 'Update failed',
  'აღდგა წინა ვერსია': 'Previous version restored',
  'განახლების სერვისი მიუწვდომელია': 'Update service unavailable',
  'განახლების სერვისთან კავშირი ვერ დამყარდა':
      'Could not connect to the update service',
  'განახლებების შემოწმება ვერ მოხერხდა': 'Could not check for updates',
  'სტატუსი მიუწვდომელია': 'Status unavailable',
  'გაუშვით POS დაყენებული Vynic-ის მალსახმობიდან.':
      'Launch POS using the installed Vynic shortcut.',
  'სცადეთ ხელახლა. დაყენებული ვერსია არ შეცვლილა.':
      'Try again. Your installed version has not changed.',
  'განახლებების სერვერი მიუწვდომელია. გადაამოწმეთ ქსელი და სცადეთ ხელახლა.':
      'Release server unavailable. Check the network and try again.',
  'ახალი ვერსიები ფონურად ჩამოიტვირთება. დაყენებას ყოველთვის თქვენ ადასტურებთ.':
      'Updates download in the background. Installation always needs your confirmation.',
  'შემოწმება': 'Check',
  'შეკვეთები და მაგიდები ინახება ამ ტერმინალზე. პროგრამის განახლებისას ისინი შენარჩუნდება.\n\nგანახლების დაყენებამდე დაასრულეთ მიმდინარე გადახდა ან მაგიდის დახურვა.':
      'Orders and tables are stored on this terminal and preserved during updates.\n\nFinish any active payment or table closing operation before installing an update.',
};
